### ISSUE TITLE
 A potential vulnerability

### ISSUE THREAD

**Issue by cgy2003** [libsdl-org/libtiff#3]
In the writeBufferToContigTiles function of the Tiffcrop.c file, there exists a potential multiplication overflow vulnerability in the following code:

if (imagewidth == 0 || (uint32_t)bps * (uint32_t)spp > UINT32_MAX / imagewidth || bps * spp * imagewidth > UINT32_MAX - 7U) {
    TIFFError(TIFFFileName(out), "Error, uint32_t overflow when computing "(imagewidth * bps * spp) + 7");
    return 1;
}
Description of the Vulnerability:
This code checks for potential overflow in the multiplication of bps * spp * imagewidth but does so in a way that still allows for the possibility of overflow, especially when the intermediate product of bps * spp is large.

Multiplication Check ((uint32_t)bps * (uint32_t)spp > UINT32_MAX / imagewidth):
The code first checks if bps * spp exceeds the threshold that would prevent an overflow when multiplied by imagewidth. However, this check is done after the multiplication of bps and spp. If the product of bps * spp is already large enough to overflow uint32_t, this check will not be able to prevent overflow.
Final Check (bps * spp * imagewidth > UINT32_MAX - 7U):
This checks if the final multiplication result of bps * spp * imagewidth will exceed UINT32_MAX after adding 7. However, this check does not protect against the possibility that the intermediate multiplication of bps * spp might overflow before being multiplied by imagewidth.
The Core Issue:
The potential overflow arises because the intermediate result of bps * spp can overflow the uint32_t type before even being checked. Only after the multiplication does the code perform overflow checks, which are insufficient for handling cases where the intermediate result exceeds UINT32_MAX.

Recommended Solution:
To mitigate this vulnerability, it is essential to use a larger data type, such as uint64_t, for intermediate calculations. Specifically, both the bps * spp and the product bps * spp * imagewidth should be computed using uint64_t to ensure that intermediate and final multiplication results are correctly checked for overflow before being cast back to uint32_t.

**Comment by madebr** [comment]
Please report this issue to upstream https://gitlab.com/libtiff/libtiff, at least if they haven't fixed it yet.

**Comment by sezero** [comment]
Closing
